name=TeensyMiraBox
version=0.1.0
author=Exit42
maintainer=Exit42
sentence=Library for connecting Mirabox devices to Teensy micro controllers
paragraph=Uses the USBHost_t36 library. Supports setting images from SD card, reading buttons, knobs and touch.
category=Device Control
url=https://github.com/rooswouter/TeensyMiraBox
architectures=*
repository=https://github.com/rooswouter/TeensyMiraBox
license=MIT
# Optional for GIF support: install AnimatedGIF and JPEGENC, define ENABLE_ANIMATEDGIF
