name=Mirabox
version=0.0.1
author=Wouter
maintainer=Wouter
sentence=Library for connecting Mirabox devices to Teensy micro controllers
paragraph=Library for connecting Mirabox devices to Teensy micro controllers
category=HID
url=https://exit42.eu
architectures=*
repository=https://github.com/???
license=???
